alice_links/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('alice_links.views',
                       url(r'^(?P<short_id>\w{6})$', 'redirect_original', name='redirectoriginal'),
                       url(r'^shortlink/$', 'add_shorten_url', name='add_shorten_url'),
                       url(r'^$', 'latest_urls', name='latest_urls'),
                       )

make_link/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'', include('alice_links.urls', namespace='alice_links')),
                       url(r'^model/', include('alice_links.urls', namespace='model')),
                       url(r'^accounts/login/$', views.login, name='login'),
                       url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
                       )

alice_links/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Urls(models.Model):
    name = models.CharField(max_length=20, blank=False, default='')
    short_id = models.SlugField(max_length=6, primary_key=True)
    http_url = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.http_url

alice_links/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Urls


class UrlsForm(forms.ModelForm):

    class Meta:
        model = Urls
        fields = ('http_url', 'name',)

alice_links/views.py
# -*- coding: utf-8 -*-
import random
import string

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from alice_links.forms import UrlsForm
from alice_links.models import Urls


def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id)
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.http_url)


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        return short_id


@login_required()
def add_shorten_url(request):
    if request.method == 'POST':
        form = UrlsForm(request.POST)
        if form.is_valid():
            b = form.cleaned_data
            url = b['http_url']
            short_id = get_short_code()
            first_name = b['name']
            b = Urls(http_url=url, short_id=short_id, name=first_name)
            b.save()
        return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')


@login_required()
def latest_urls(request):
    urls_list = Urls.objects.order_by('-pub_date')[:5]
    return render(request, 'alice_links/index.html', {'urls_list': urls_list})

alice_links/templates/alice_links/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'alice_links/css/styles.css' %}"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">Мой сервис для уменьшения ссылок</a>
            </div>
            {% if user.is_authenticated %}
                <p class="navbar-text navbar-right">&nbsp;{{ user.username }}&nbsp;<a class="navbar-link"
                                                                                 href="{% url 'logout' %}">(&nbsp;Выйти&nbsp;)</a></p>
            {% else %}
                <p class="navbar-text navbar-right"><a class="navbar-link" href="{% url 'login' %}">&nbsp;Войти</a></p>
            {% endif %}
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% block shortlink %}{% endblock %}
                {% block login %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

alice_links/templates/alice_links/index.html
{% extends 'alice_links/base.html' %}

{% block shortlink %}
    <div class="col-md-12">
        <form class="form-inline input" role="form" action="{% url 'model:add_shorten_url' %}" method="post"
              autocomplete="on">
            {% csrf_token %}
            <label for="id_http_url">Введите вашу ссылку:</label>
            <input class="form-control" id="id_http_url" required maxlength="200" name="http_url" type="url" value=""
                   placeholder="https://twitter.com/"/>
            <button type="submit" class="btn btn-success">Уменьшить</button>
            <label for="id_name"></label>
            <input id="id_name" maxlength="20" name="name" type="text" value="{{ user.username }}"/>
        </form>
        <table class="table table-striped">
            {% for urls in urls_list %}
                <tr>
                    <td>Длинная ссылка:</td>
                    <td><a href="{{ urls.http_url }}" target="_blank">{{ urls.http_url }}</a></td>
                    <td>Коротка ссылка:</td>
                    <td><a href="../{{ urls.short_id }}" target="_blank"
                           title="Для использования скопируйте адрес ссылки">{{ urls.short_id }}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}